from . import res_company
from . import res_partner
from . import mail_channel
from . import mail_message
from . import whatsapp
from . import res_partner
from . import whatsapp_template
from . import whatsapp_template_button
from . import whatsapp_template_variable
from . import whatsapp_flow
from . import whatsapp_trigger_messages
